### ISSUE TITLE
Need comparison between behavior of edge server with this

### ISSUE THREAD

**Issue by webuniverseio** [akamai/esi-test-server-docker#11]
Hi, similar to https://github.com/akamai/esi-test-server-docker#caveats section, would it be possible to add a comparison between behavior or using esi on edge and using this image? What other known differences can developers expect? This information will help to design around potential incompatibilities. **Update 2018-11-04** if anyone want to continue this discussion on SO, here is a [link](https://stackoverflow.com/questions/53000671/are-there-any-known-differences-between-using-akamai-esi-via-ets-and-using-it-on).

Also quick question - do you know if https://developer.akamai.com/tools/akamai-sandbox will also include ESI support?

Thank you so much!

**Comment by akhiljay** [comment]
Hi Szarouski, The Akamai Sandbox does support ESI testing. Please feel free to sign up here https://bit.ly/sandbox-early-access  to get access to the Sandbox.

**Comment by webuniverseio** [comment]
Hi @akhiljay, this is amazing to hear! I signed up last week, waiting for reply. Thanks.
