### ISSUE TITLE
Debug ESI Locally

### ISSUE THREAD

**Issue by dariobanfi** [akamai/esi-test-server-docker#14]
Hi,

I am not sure if I misunderstood what I can do with this container, but I just can't manage to get an `esi:include` working:

Steps:

1) Add a mapping `macbook.local 127.0.0.1` to my /etc/hosts

2) Start a server on port `3000` with a page containing a tag `<esi:include src="https://www.google.com/"` which serves the page on `http://macbook.local:3000/test/index.html`

3) Run the command `docker run -ti 8080:80 akamaiesi/ets-docker:latest --remote_origin macbook.local:3000`

4) Try to do a request with the Host header `curl -H 'Host: macbook.local' 'macbook.local:8080/test/index.html'`

I get a `503 Service Unavailable`.
Is there something wrong is those steps? Any tip?

**Comment by dariobanfi** [comment]
I tried to simplify even more:

1. Serve esi page on macbook.local:80, which includes a local html page in the same folder

2. Run `docker run -p 8282:80 akamaiesi/ets-docker:latest --remote_origin macbook.local`

3. Run `curl -H 'Host:macbook.local' localhost:8282`

4. Output is `Nothing to see here` 🤔

**Comment by sjoulano** [comment]
Dario, could you please provide:
1. `docker run` command, and its output;
2. output of curl http://macbook.local/

Also, check if URI at <esi:include> tag is reachable from the container.
Another hint: you can run ETS container with ESI debugging (--debug flag), e.g.:
`docker run -ti -p 8282:80 akamaiesi/ets-docker:latest --remote_origin macbook.local --debug macbook.local`
You will get debugging info at curl output.

**Comment by Gopi-Thumati** [comment]
@dariobanfi  How did you resolve this problem?

**Comment by dariobanfi** [comment]
Honestly I don't remember, I vaguely recall using another JS-based library that emulated the functionality @Gopi-Thumati
