### ISSUE TITLE
Exceeding the maximum response size limit

### ISSUE THREAD

**Issue by yossarian21** [akamai/esi-test-server-docker#7]
I can see in the release_notes.txt of akami-ets_6.0.0.8_ubuntu.tar.gz that the maximum response size limit is 2MB.  We are exceeding that limit on one of our responses; is there a way I can provide a configuration setting to the container with a higher limit?

**Comment by yossarian21** [comment]
It looks like this could be done via the page_size_limit option, but it looks like the resulting Apache configuration is put in the wrong place.  This is what's in esi_map_0.conf:

```xml
<VirtualHost *:80>
	ServerName <ip-omitted>
    <IfModule mod_headers.c>
        Header unset Content-Security-Policy
    </IfModule>
    <IfModule mod_esi.c>
    	ESI on
	    ESITimeout 30
		ESIDebugging off
		GEO georegion=246,country_code=US,region_code=CA,city=SANJOSE,dma=807,pmsa=7400,
areacode=408,county=SANTACLARA,fips=06085,lat=37.3353,long=-121.8938,timezone=PST,network_type=d
ialup
	</IfModule>
	<IfModule mod_proxy.c>
		ProxyPass / http://<ip-omitted>:8080/
		ProxyPassReverse / http://<ip-omitted>:8080/
   		<Directory proxy:*>
         		Order allow,deny
        		Allow from all
       		</Directory>
        	SurrogateHeader Surrogate-Capability "ESI/1.0"
        	ChaseRedirects on
	</IfModule>
    <IfModule deflate_module>
        SetOutputFilter INFLATE
    </IfModule>
	MetaData dca-max-output-size 5000000
</VirtualHost>
```

I think MetaData dca-max-output-size should be inside IfModule mod_esi.c section?

**Comment by umeshtiwari23** [comment]
I think the limit is still 1MB on release 6.0.0.9 and the --page_size_limit option doesn't change the behaviour.
I am using akamaiesi/ets-docker:6.0.0.9 with command --page_size_limit 4000000
My page size is 1033701 and still fails as it is exceeding 1MB

@yossarian21 were you able to resolve the issue?

**Comment by yossarian21** [comment]
No, and as it turns out, we wouldn't want to change our production Akamai limit of approximately 1.25MB anyway (even if we could).  So I fixed my problem by making sure our pages are smaller.  I'll close this ticket.
